/**
  рейтинг МРА
 */
CREATE TABLE if not exists mpa
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_mpa varchar(255),
    CONSTRAINT uq_name_mpa UNIQUE (name_mpa)
);
/**
  таблица с фильмами
 */
CREATE TABLE if not exists films
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_film   varchar(255) NOT NULL,
    description varchar(255) NOT NULL,
    releaseDate timestamp,
    duration    integer,
    mpa_id      integer references mpa (id),
    CONSTRAINT uq_films_name UNIQUE (name_film)
);
/**
  таблица пользователей сайта
 */
CREATE TABLE if not exists users
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login     varchar(255) not null,
    name_user varchar(255),
    email     varchar(255),
    birthday  timestamp,
    CONSTRAINT uq_login UNIQUE (login)
);
/**
  таблица лайтов пользователей за фильм
 */
CREATE TABLE if not exists likes
(
    films_id integer references films (id) ON DELETE CASCADE,
    users_id integer references users (id) ON DELETE CASCADE,
    primary key (films_id, users_id)
);
/**
  таблица жаннов фильма
 */
CREATE TABLE if not exists genre
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_genre varchar(255),
    CONSTRAINT uq_name_genre UNIQUE (name_genre)
);
/**
  таблица связывающая фильм и его жанр. жантов может быть несколько
 */
CREATE TABLE if not exists film_genre
(
    id_films integer references films (id) ON DELETE CASCADE,
    id_genre integer references genre (id) ON DELETE CASCADE
);
/**
  таблица друзей
 */

CREATE TABLE if not exists users_friends
(
    first_user  integer references users (id) ON DELETE CASCADE,
    second_user integer references users (id) ON DELETE CASCADE,
    primary key (first_user, second_user)
);
